# Generated by Django 5.2.10 on 2026-01-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название локации')),
                ('description_short', models.CharField(blank=True, default='', max_length=400, verbose_name='Краткое описание')),
                ('description_long', models.TextField(verbose_name='Полное описание')),
                ('lng', models.DecimalField(blank=True, decimal_places=14, max_digits=17, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Широта')),
            ],
        ),
    ]
