# Generated by Django 5.2.10 on 2026-01-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Долгота'),
        ),
    ]
